#!/bin/sh
sudo cpufreq-set -g performance
#echo 'lxde' >> /tmp/my_log_x
date >> /tmp/my_log_x
export GOOGLE_API_KEY="no"
export GOOGLE_DEFAULT_CLIENT_ID="no"
export GOOGLE_DEFAULT_CLIENT_SECRET="no"
chromium -kiosk -incognito http://127.0.0.1:8888/ --disable-translate &
#node /home/debian/kopex/node/x_agent.js > /tmp/log_x.txt &
#forever start /home/debian/kopex/node/main.js &
#forever start /home/debian/kopex/node/zapisDoPliku.js &
cd /home/debian/kopex/
npm start &
npm run zapis &
