#!/bin/sh

echo 'deb' >> /tmp/my_log
date >> /tmp/my_log
cpufreq-set -g performance
node /home/debian/kopex/tcp_cl3.js &

#echo ds1307 0x68>/sys/class/i2c-adapter/i2c-1/new_device
#hwclock -s -f /dev/rtc1
#hwclock -w
#node /home/olimex/kopex/tcp_cl3.js &

#xdotool mousemove --sync 1024 300 &
#rm /home/olimex/.mozilla/firefox/*.default/sessionstore.js
#rm /home/olimex/.mozilla/firefox/*.default/sessionstore.bak
#sleep 5 && iceweasel -fullscreen http://127.0.0.1:8888

#cpufreq-set -g performance
#export GOOGLE_API_KEY="no"
#export GOOGLE_DEFAULT_CLIENT_ID="no"
#export GOOGLE_DEFAULT_CLIENT_SECRET="no"
#chromium -kiosk -incognito http://127.0.0.1:8888/min/ --disable-translate &

#sleep 16 && xdotool mousemove --sync 465 20 click 1 && sleep 1 && xdotool mousemove --sync 0 0 &

#hostname -I
#whoami 
#export DISPLAY=':0'
