#!/bin/sh

echo 'lxde' >> /tmp/my_log
date >> /tmp/my_log
export GOOGLE_API_KEY="no"
export GOOGLE_DEFAULT_CLIENT_ID="no"
export GOOGLE_DEFAULT_CLIENT_SECRET="no"
chromium -kiosk -incognito http://127.0.0.1:8888/ --disable-translate &
